name = "packershub"
compatibility_date = "2026-06-28"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "TRACKING_KV"
# id = "REPLACE_WITH_YOUR_NAMESPACE_ID"

[vars]
SITE_URL = "https://packershub.in"

[assets]
directory = "dist"
binding = "STATIC_ASSETS"