import { defineMiddleware } from "astro:middleware";

const REDIRECTS: Record<string, string> = {
  "/home": "/",
  "/warehouse-storage": "/storage-warehousing",
  "/packers-movers-visakhapatnam/": "/andhra-pradesh/visakhapatnam/",
  "/packers-movers-vijayawada/": "/andhra-pradesh/vijayawada/",
  "/packers-movers-guntur/": "/andhra-pradesh/guntur/",
  "/packers-movers-nellore/": "/andhra-pradesh/nellore/",
  "/packers-movers-kurnool/": "/andhra-pradesh/kurnool/",
  "/packers-movers-rajahmundry/": "/andhra-pradesh/rajahmundry/",
  "/packers-movers-kakinada/": "/andhra-pradesh/kakinada/",
  "/packers-movers-tirupati/": "/andhra-pradesh/tirupati/",
  "/packers-movers-eluru/": "/andhra-pradesh/eluru/",
  "/packers-movers-ongole/": "/andhra-pradesh/ongole/",
  "/packers-movers-vizianagaram/": "/andhra-pradesh/vizianagaram/",
  "/packers-movers-srikakulam/": "/andhra-pradesh/srikakulam/",
  "/packers-movers-anantapur/": "/andhra-pradesh/anantapur/",
  "/packers-movers-chittoor/": "/andhra-pradesh/chittoor/",
  "/packers-movers-kadapa/": "/andhra-pradesh/kadapa/",
  "/packers-movers-tanuku/": "/andhra-pradesh/",
  "/packers-movers-narasaraopet/": "/andhra-pradesh/",
  "/packers-movers-machilipatnam/": "/andhra-pradesh/machilipatnam/",
  "/packers-movers-palakollu/": "/andhra-pradesh/",
  "/packers-movers-bhimavaram/": "/andhra-pradesh/bhimavaram/",
  "/packers-movers-hyderabad/": "/telangana/hyderabad/",
  "/packers-movers-warangal/": "/telangana/warangal/",
  "/packers-movers-nizamabad/": "/telangana/nizamabad/",
  "/packers-movers-khammam/": "/telangana/khammam/",
  "/packers-movers-karimnagar/": "/telangana/karimnagar/",
  "/packers-movers-ramagundam/": "/telangana/ramagundam/",
  "/packers-movers-mahbubnagar/": "/telangana/mahbubnagar/",
  "/packers-movers-nalgonda/": "/telangana/nalgonda/",
  "/packers-movers-adilabad/": "/telangana/adilabad/",
  "/packers-movers-suryapet/": "/telangana/suryapet/",
  "/packers-movers-siddipet/": "/telangana/siddipet/",
  "/packers-movers-jagtial/": "/telangana/jagtial/",
  "/packers-movers-medchal/": "/telangana/",
  "/packers-movers-sangareddy/": "/telangana/",
  "/packers-movers-miryalaguda/": "/telangana/miryalaguda/",
  "/packers-movers-jangaon/": "/telangana/jangaon/",
  "/packers-movers-narayanpet/": "/telangana/",
  "/packers-movers-bhadradri-kothagudem/": "/telangana/kothagudem/",
  "/packers-movers-nirmal/": "/telangana/",
  "/packers-movers-bhuvanagiri/": "/telangana/",
  "/packers-movers-chennai/": "/tamil-nadu/chennai/",
  "/packers-movers-coimbatore/": "/tamil-nadu/coimbatore/",
  "/packers-movers-madurai/": "/tamil-nadu/madurai/",
  "/packers-movers-tiruchirappalli/": "/tamil-nadu/tiruchirappalli/",
  "/packers-movers-salem/": "/tamil-nadu/salem/",
  "/packers-movers-tirunelveli/": "/tamil-nadu/tirunelveli/",
  "/packers-movers-tiruppur/": "/tamil-nadu/tiruppur/",
  "/packers-movers-vellore/": "/tamil-nadu/vellore/",
  "/packers-movers-erode/": "/tamil-nadu/erode/",
  "/packers-movers-thoothukudi/": "/tamil-nadu/thoothukudi/",
  "/packers-movers-dindigul/": "/tamil-nadu/dindigul/",
  "/packers-movers-thanjavur/": "/tamil-nadu/thanjavur/",
  "/packers-movers-ranipet/": "/tamil-nadu/ranipet/",
  "/packers-movers-kanchipuram/": "/tamil-nadu/kanchipuram/",
  "/packers-movers-cuddalore/": "/tamil-nadu/",
  "/packers-movers-nagapattinam/": "/tamil-nadu/",
  "/packers-movers-krishnagiri/": "/tamil-nadu/",
  "/packers-movers-virudhunagar/": "/tamil-nadu/",
  "/packers-movers-pudukkottai/": "/tamil-nadu/",
  "/packers-movers-ooty/": "/tamil-nadu/udhagamandalam/",
  "/packers-movers-bengaluru/": "/karnataka/bangalore/",
  "/packers-movers-mysuru/": "/karnataka/mysore/",
  "/packers-movers-hubballi/": "/karnataka/hubli/",
  "/packers-movers-mangaluru/": "/karnataka/mangalore/",
  "/packers-movers-belagavi/": "/karnataka/belgaum/",
  "/packers-movers-kalaburagi/": "/karnataka/gulbarga/",
  "/packers-movers-ballari/": "/karnataka/bellary/",
  "/packers-movers-bidar/": "/karnataka/bidar/",
  "/packers-movers-davanagere/": "/karnataka/davanagere/",
  "/packers-movers-shivamogga/": "/karnataka/shimoga/",
  "/packers-movers-tumakuru/": "/karnataka/tumkur/",
  "/packers-movers-raichur/": "/karnataka/raichur/",
  "/packers-movers-vijayapura/": "/karnataka/bijapur/",
  "/packers-movers-hassan/": "/karnataka/hassan/",
  "/packers-movers-chitradurga/": "/karnataka/chitradurga/",
  "/packers-movers-madikeri/": "/karnataka/",
  "/packers-movers-udupi/": "/karnataka/udupi/",
  "/packers-movers-chikkamagaluru/": "/karnataka/",
  "/packers-movers-kolar/": "/karnataka/kolar/",
  "/packers-movers-gadag/": "/karnataka/gadag/",
  "/packers-movers-thiruvananthapuram/": "/kerala/thiruvananthapuram/",
  "/packers-movers-kochi/": "/kerala/kochi/",
  "/packers-movers-kozhikode/": "/kerala/kozhikode/",
  "/packers-movers-thrissur/": "/kerala/thrissur/",
  "/packers-movers-kollam/": "/kerala/kollam/",
  "/packers-movers-palakkad/": "/kerala/palakkad/",
  "/packers-movers-alappuzha/": "/kerala/alappuzha/",
  "/packers-movers-kannur/": "/kerala/kannur/",
  "/packers-movers-kottayam/": "/kerala/kottayam/",
  "/packers-movers-malappuram/": "/kerala/malappuram/",
  "/packers-movers-kasaragod/": "/kerala/kasaragod/",
  "/packers-movers-pathanamthitta/": "/kerala/pathanamthitta/",
  "/packers-movers-wayanad/": "/kerala/wayanad/",
  "/packers-movers-idukki/": "/kerala/idukki/",
  "/packers-movers-neyyattinkara/": "/kerala/",
  "/packers-movers-angamaly/": "/kerala/",
  "/packers-movers-chalakudy/": "/kerala/",
  "/packers-movers-perinthalmanna/": "/kerala/perinthalmanna/",
  "/packers-movers-thodupuzha/": "/kerala/",
  "/packers-movers-nilambur/": "/kerala/",
  "/about": "/about/",
  "/services": "/services/",
  "/vehicle-transport": "/vehicle-transport/",
  "/storage-warehousing": "/storage-warehousing/",
  "/booking": "/booking/",
  "/track": "/track/",
  "/franchise": "/franchise/",
  "/blog": "/blog/",
  "/contact": "/contact/",
  "/privacy": "/privacy/",
  "/terms": "/terms/",
  "/andhra-pradesh": "/andhra-pradesh/",
  "/telangana": "/telangana/",
  "/tamil-nadu": "/tamil-nadu/",
  "/karnataka": "/karnataka/",
  "/kerala": "/kerala/",
  "/home-shifting-services": "/home-shifting-services/",
  "/office-relocation-services": "/office-relocation-services/",
  "/car-transportation": "/car-transportation/",
  "/bike-transportation": "/bike-transportation/",
  "/international-relocation": "/international-relocation/",
  "/local-shifting": "/local-shifting/",
  "/intercity-shifting": "/intercity-shifting/",
  "/industrial-shifting": "/industrial-shifting/",
  "/packing-services": "/packing-services/",
};

export const onRequest = defineMiddleware((context, next) => {
  const url = new URL(context.request.url);
  const path = url.pathname;

  // Exact match redirects
  if (REDIRECTS[path]) {
    return context.redirect(REDIRECTS[path], 301);
  }

  // Wildcard: /packers-movers-* -> /
  if (path.startsWith("/packers-movers-")) {
    return context.redirect("/", 301);
  }

  // Trailing slash redirects for state/city paths
  const stateMatch = path.match(/^\/((andhra-pradesh|telangana|tamil-nadu|karnataka|kerala)\/[a-z0-9-]+)$/);
  if (stateMatch) {
    return context.redirect("/" + stateMatch[1] + "/", 301);
  }

  return next();
});
